import test from 'node:test';import assert from 'node:assert/strict';
const memory=new Map();global.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};global.sessionStorage={getItem:key=>memory.get(`s:${key}`)??null,setItem:(key,value)=>memory.set(`s:${key}`,value),removeItem:key=>memory.delete(`s:${key}`)};
const {BASE_WORDS}=await import('../data/words/index.js');const {RECIPES,resolveRecipe}=await import('../data/recipes.js');const {normalizeWord,isPhysicalSubject}=await import('../js/semantic-layer.js');const {newDrop,replaceUnlocked,addWord,removeOptional,validateDrop}=await import('../js/random-engine.js');const {buildSentence}=await import('../js/sentence-builder.js');const storage=await import('../js/storage.js');
const word=text=>BASE_WORDS.find(item=>item.text===text);

test('semantic normalization keeps legacy and user words compatible',()=>{const legacy=normalizeWord({id:'u',text:'自制盒子',category:'container'});assert.ok(legacy.roles.includes('subject'));assert.equal(legacy.domain,'unknown');assert.deepEqual(normalizeWord(word('没有出口')).roles,['concept','anomaly_rule'])});
test('twelve visual skeletons declare required and optional roles',()=>{assert.equal(RECIPES.length,12);for(const recipe of RECIPES){assert.ok(recipe.required.length>=3);assert.ok(recipe.optional.length);assert.ok(recipe.required.some(slot=>slot.role==='subject'))}assert.equal(resolveRecipe('concept_stage').id,'space_closure');assert.equal(resolveRecipe('missing').id,'wrong_contents')});
test('100 drops are valid, physical and complete without duplicate ids',()=>{for(let i=0;i<100;i++){const drop=newDrop(i%3+3,[],null,'odd'),check=validateDrop(drop);assert.ok(check.valid,`${drop.recipe.id}: ${JSON.stringify(check)}`);assert.ok(isPhysicalSubject(drop.words.find(w=>w.role==='subject')));assert.ok(drop.recipe.required.every(slot=>drop.words.some(w=>w.role===slot.role)));assert.equal(new Set(drop.words.map(w=>w.id)).size,drop.words.length);assert.ok(drop.words.every(w=>w&&w.id&&w.text))}});
test('repeated drops cover every skeleton',()=>{const seen=new Set(Array.from({length:600},()=>newDrop(4).recipe.id));assert.deepEqual([...seen].sort(),RECIPES.map(r=>r.id).sort())});
test('creative distances have distinct optional depth',()=>{const recipe=resolveRecipe('wrong_contents'),near=Array.from({length:30},()=>newDrop(5,[],recipe,'near')),wild=Array.from({length:30},()=>newDrop(4,[],recipe,'wild'));assert.ok(near.every(drop=>drop.distance==='near'&&drop.words.length<=4));assert.ok(wild.every(drop=>drop.distance==='wild'&&drop.words.length>=5))});
test('locks use roles for object, observation, and concept',()=>{for(const text of ['板装药片','药板背面的银色凹痕','没有出口']){const locked={...word(text),locked:true},drop=newDrop(5,[locked]);assert.ok(drop.words.some(w=>w.id===locked.id&&w.locked));assert.ok(isPhysicalSubject(drop.words.find(w=>w.role==='subject')))}const conceptDrop=newDrop(5,[{...word('没有出口'),locked:true}]);assert.notEqual(conceptDrop.words.find(w=>w.role==='subject').text,'没有出口');assert.ok(['concept','anomaly'].includes(conceptDrop.words.find(w=>w.text==='没有出口').role))});
test('observations only fill observation/detail anomaly roles',()=>{for(const text of ['药板背面的银色凹痕','便利店冰柜门上的冷凝水','公交车窗玻璃上干掉的雨水痕迹','旧收据上逐渐褪去的字']){const drop=newDrop(5,[{...word(text),locked:true}]);const placed=drop.words.find(w=>w.text===text);assert.ok(['anomaly','detail'].includes(placed.role));assert.notEqual(placed.role,'subject')}});
test('again, add one and less preserve skeleton invariants',()=>{let drop=newDrop(3);drop.words[0].locked=true;const next=replaceUnlocked(drop.words,drop.recipe);assert.equal(next.recipe.id,drop.recipe.id);assert.ok(next.words.some(w=>w.locked&&w.id===drop.words[0].id));const added=addWord(next.words,next.recipe);assert.ok(added.words.length<=5);const less=removeOptional(added.words,added.recipe);for(const required of added.recipe.required)assert.ok(less.some(w=>w.role===required.role))});
test('dozens of role-aware mixes use only dropped words and safe grammar',()=>{const banned=['一处空白房间','半透明材料','冷白漫射光','细小的表面痕迹','没有出口彼此贴合'];const structures=new Set();for(let i=0;i<60;i++){const drop=newDrop(5),short=buildSentence(drop.words,drop.recipe,'short'),expanded=buildSentence(drop.words,drop.recipe,'expanded');structures.add(drop.recipe.id);for(const output of [short,expanded]){assert.ok(output.endsWith('。'));for(const phrase of banned)if(!drop.words.some(w=>w.text===phrase))assert.ok(!output.includes(phrase));assert.ok(!output.includes('undefined'));assert.ok(!output.includes('null'))}}assert.ok(structures.size>=8)});
test('v1 storage keys and payloads remain readable',()=>{storage.addMyWord({id:'user_1',text:'雨痕',category:'detail'});assert.equal(JSON.parse(localStorage.getItem('wm-my-words-v1'))[0].text,'雨痕');const drop=newDrop(4);storage.setMachineState(drop);storage.saveDrop({...drop,recipe:'一句话'});assert.ok(localStorage.getItem('wm-machine-v1'));assert.ok(localStorage.getItem('wm-saved-v1'));assert.equal(storage.getSaved()[0].recipe,'一句话')});
