import test from 'node:test';import assert from 'node:assert/strict';
const memory=new Map();global.localStorage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};global.sessionStorage={getItem:key=>memory.get(`s:${key}`)??null,setItem:(key,value)=>memory.set(`s:${key}`,value),removeItem:key=>memory.delete(`s:${key}`)};
const {BASE_WORDS}=await import('../data/words/index.js');const {VISUAL_OPERATIONS}=await import('../data/visual-operations.js');const {normalizeWord}=await import('../js/semantic-layer.js');const {newDrop,replaceUnlocked,addWord,removeOptional,validateDrop,composeFixture}=await import('../js/random-engine.js');const {buildSentence}=await import('../js/sentence-builder.js');const storage=await import('../js/storage.js');
const word=(text,category='object')=>BASE_WORDS.find(item=>item.text===text)||{id:`fixture_${text}`,text,category};
const fixture=(operation,texts,mode='odd')=>composeFixture(operation,texts.map(item=>Array.isArray(item)?word(...item):word(item)),mode);

test('defines exactly twelve operation-first visual operations',()=>{assert.equal(VISUAL_OPERATIONS.length,12);assert.equal(new Set(VISUAL_OPERATIONS.map(x=>x.id)).size,12);for(const op of VISUAL_OPERATIONS){assert.ok(op.subjects.length&&op.sources.length);assert.equal(op.id,op.id.toUpperCase())}});
test('semantic normalization protects concepts, observations, visuals and scales from subject use',()=>{assert.deepEqual(normalizeWord(word('没有出口')).roles,['concept','anomaly_rule']);for(const text of ['药板背面的银色凹痕','便利店冰柜门上的冷凝水'])assert.ok(normalizeWord(word(text)).roles.includes('observation_source'))});
test('fixture A: aquarium contains abnormal medicine contents',()=>{const p=fixture('WRONG_CONTENTS',['鱼缸','板装药片']);assert.equal(p.subject.text,'鱼缸');assert.equal(p.anomalySource.text,'板装药片');assert.match(p.relation,/鱼缸内部/);assert.ok(p.validation.valid)});
test('fixture B: condensation transfers toward plaster surface',()=>{const p=fixture('SURFACE_TRANSFER',[['石膏头像','object'],'便利店冰柜门上的冷凝水']);assert.equal(p.target,'石膏头像表面');assert.match(p.relation,/转移到石膏头像表面/);assert.ok(p.validation.valid)});
test('fixture C: frame structure replaces camera bag structure',()=>{const p=fixture('STRUCTURE_REPLACEMENT',['相机包','相框']);assert.equal(p.target,'相机包的外部结构');assert.match(p.relation,/外部结构被替换成相框/);assert.doesNotMatch(p.relation,/发生/);assert.ok(p.validation.valid)});
test('fixture D: wild closure uses all six ingredients and a secondary surface operation',()=>{const p=fixture('SPATIAL_CLOSURE',['浴室','周转箱','像家具一样大','重复成一条边界','药板背面的银色凹痕','冷白顶光'],'wild');assert.equal(p.subject.text,'周转箱');assert.equal(p.space.text,'浴室');assert.equal(p.secondaryOperation.operation,'SURFACE_TRANSFER');assert.equal(p.usedWordIds.length,6);for(const text of ['浴室','周转箱','像家具一样大','重复成一条边界','药板背面的银色凹痕','冷白顶光'])assert.ok(JSON.stringify(p).includes(text));assert.ok(p.validation.valid)});
test('fixture E: receipt trace is a magnifiable observation, not an ordinary object',()=>{const p=fixture('OBSERVATION_MAGNIFY',['旧收据上逐渐褪去的字']);assert.equal(p.anomalySource.category,'observation');assert.match(p.relation,/放大/);assert.ok(p.validation.valid)});
test('fixture F: no exit remains a rule while rack is physical structure',()=>{const p=fixture('SPATIAL_CLOSURE',[['没有出口','concept'],['阳台','space'],['金属晾衣架','object']]);assert.equal(p.subject.text,'金属晾衣架');assert.equal(p.space.text,'阳台');assert.equal(p.anomalySource.text,'没有出口');assert.ok(p.validation.valid)});
test('300 generated plans pass quality metrics in NEAR, ODD and WILD',()=>{const stats={total:0,subjects:0,operations:0,directed:0,valid:0,retries:0,observations:0,conceptSubjects:0,visualSubjects:0,scaleSubjects:0,nulls:0,duplicates:0};for(const mode of ['near','odd','wild'])for(let i=0;i<100;i++){const d=newDrop(mode==='wild'?6:4,[],null,mode),p=d.scenePlan;stats.total++;stats.subjects+=!!p.subject?.text;stats.operations+=!!p.operation;stats.directed+=!!p.target&&!!p.transformation&&p.relation.length>9;stats.valid+=p.validation.valid;stats.retries+=d.retries;stats.observations+=p.ingredients.filter(w=>w.category==='observation'&&p.usedWordIds.includes(w.id)).length;stats.conceptSubjects+=p.subject?.category==='concept';stats.visualSubjects+=p.subject?.category==='visual';stats.scaleSubjects+=p.subject?.category==='scale';stats.nulls+=/undefined|null/.test(buildSentence(p,null,'expanded'));stats.duplicates+=new Set(p.ingredients.map(w=>w.id)).size!==p.ingredients.length}assert.equal(stats.total,300);assert.equal(stats.subjects,300);assert.equal(stats.operations,300);assert.equal(stats.directed,300);assert.equal(stats.valid,300);assert.ok(stats.retries<30);assert.equal(stats.conceptSubjects,0);assert.equal(stats.visualSubjects,0);assert.equal(stats.scaleSubjects,0);assert.equal(stats.nulls,0);assert.equal(stats.duplicates,0);assert.ok(stats.observations>=0)});
test('sentence builder uses directed plans and rejects legacy filler phrases',()=>{const banned=['与相框发生','发生悬挂于','发生覆盖','发生穿插','银色高光照亮两者','冷白光照亮两者','熟悉的轮廓','难以解释','形成超现实感','产生陌生感'];for(let i=0;i<120;i++){const p=newDrop(6,[],null,i%3===0?'near':i%3===1?'odd':'wild').scenePlan;for(const mode of ['short','expanded']){const output=buildSentence(p,null,mode);assert.ok(output.endsWith('。'));for(const phrase of banned)assert.ok(!output.includes(phrase),output)}}});
test('AGAIN keeps primary operation and locks; ADD ONE and LESS only change optionals',()=>{let d=newDrop(4,[],null,'wild');d.words[0].locked=true;const again=replaceUnlocked(d.words,d.operation,'wild');assert.equal(again.operation.id,d.operation.id);assert.ok(again.words.some(w=>w.locked&&w.id===d.words[0].id));const added=addWord(again.words,again.operation,'wild');assert.equal(added.scenePlan.subject.text,again.scenePlan.subject.text);const less=removeOptional(added.words,added.operation,'wild');assert.ok(less.words.some(w=>w.sceneRole==='subject'));assert.ok(less.words.some(w=>w.sceneRole==='source'));assert.ok(validateDrop(less).valid)});
test('v1 storage keys and legacy saved ideas remain readable',()=>{storage.addMyWord({id:'user_1',text:'雨痕',category:'detail'});storage.setMachineState({words:[word('鱼缸')],recipeId:'wrong_contents'});storage.saveDrop({words:[word('鱼缸')],recipe:'旧句子'});assert.equal(JSON.parse(localStorage.getItem('wm-my-words-v1'))[0].text,'雨痕');assert.equal(storage.getMachineState().recipeId,'wrong_contents');assert.equal(storage.getSaved()[0].recipe,'旧句子');assert.ok(localStorage.getItem('wm-machine-v1')&&localStorage.getItem('wm-saved-v1'))});
test('v3 ingredients persist independently without overwriting legacy data',()=>{const originalWords=localStorage.getItem('wm-my-words-v1'),originalSaved=localStorage.getItem('wm-saved-v1');storage.addIngredient(word('鱼缸'));storage.addIngredient(word('鱼缸'));storage.addIngredient(word('相框'));assert.deepEqual(storage.getIngredients().map(x=>x.text),['鱼缸','相框']);storage.removeIngredient(storage.getIngredients()[0].id);assert.deepEqual(storage.getIngredients().map(x=>x.text),['相框']);assert.equal(localStorage.getItem('wm-my-words-v1'),originalWords);assert.equal(localStorage.getItem('wm-saved-v1'),originalSaved);assert.ok(localStorage.getItem('wm-ingredients-v3'));storage.clearIngredients();assert.deepEqual(storage.getIngredients(),[])});
