import test from 'node:test';import assert from 'node:assert/strict';
const memory=new Map();global.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
const {BASE_WORDS,CATEGORIES}=await import('../data/words/index.js');const {RECIPES}=await import('../data/recipes.js');const {newDrop,replaceUnlocked,addWord}=await import('../js/random-engine.js');const {buildSentence}=await import('../js/sentence-builder.js');const storage=await import('../js/storage.js');
test('modular bank has 1000–1500 valid visual units',()=>{assert.ok(BASE_WORDS.length>=1000&&BASE_WORDS.length<=1500);assert.equal(new Set(BASE_WORDS.map(w=>w.id)).size,BASE_WORDS.length);for(const w of BASE_WORDS){assert.ok(w.id&&w.text&&CATEGORIES.includes(w.category)&&w.subcategory&&Array.isArray(w.tags)&&w.source&&w.weight>0)}});
test('all recipe slots have source data',()=>{for(const recipe of RECIPES)for(const slot of recipe.slots)assert.ok(BASE_WORDS.some(w=>w.category===slot),`${recipe.id}: ${slot}`)});
test('drop follows recipe and respects requested count',()=>{for(const count of [3,4,5]){const d=newDrop(count);assert.equal(d.words.length,count);assert.ok(d.words.every(w=>d.recipe.slots.includes(w.category)))}});
test('again keeps locked words and replaces unlocked',()=>{const d=newDrop(4);d.words[0].locked=true;const before=d.words.map(w=>w.id),next=replaceUnlocked(d.words,d.recipe);assert.equal(next.words[0].id,before[0]);assert.equal(next.words[0].locked,true);assert.ok(next.words.slice(1).some((w,i)=>w.id!==before[i+1]))});
test('one more caps at five and sentence is natural output',()=>{let d=newDrop(3);d=addWord(d.words,d.recipe);assert.equal(d.words.length,4);d=addWord(d.words,d.recipe);d=addWord(d.words,d.recipe);assert.equal(d.words.length,5);assert.ok(buildSentence(d.words,d.recipe).endsWith('。'))});
test('user words and saved drops persist',()=>{storage.addMyWord({id:'user_1',text:'雨痕',category:'detail',tags:[],source:'user',weight:1});assert.equal(storage.getMyWords()[0].text,'雨痕');const d=newDrop(3);storage.saveDrop({...d,recipe:'一句话'});assert.equal(storage.getSaved().length,1);assert.equal(storage.getSaved()[0].recipe,'一句话')});
